server:
  port: '8080'
spring:
  datasource:
    password: ''
    url: jdbc:h2:file:/tmp/h2
    username: sa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        connection:
          isolation: '2'
        default_schema: spring_boot_starter_web_boot
        format_sql: 'true'
        generate_statistics: 'true'
        hbm2ddl:
          auto: update
        jdbc:
          batch_size: '5'
          fetch_size: '5'
        packagesToScan: idv.hsiehpinghan.springbootstarterwebkubernetes.**.entity
        show_sql: 'true'
        use_sql_comments: 'true'
  thymeleaf:
    mode: HTML
logging:
  level:
    idv.hsiehpinghan: INFO
    root: INFO

